# Generated by Django 4.1.2 on 2025-02-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created']},
        ),
    ]
